@startuml

'skinparam monochrome true
'skinparam classBackgroundColor White
skinparam classArrowColor Black
skinparam classBorderColor Black
skinparam stereotypeCBackgroundColor Gray
'hide members
hide circle

class CypherService {
    ~constructor()
    +profile(query)
    +send(query)
    +transaction() : CypherTransaction
    -transactionStarted(id, transaction)
    -transactionFinished(id)
    -rollbackAllTransactions()
    -getTransactionIDs()
    -promiseResult()
}

class CypherTransaction {
    ~constructor()
    +begin(query)
    +execute(query)
    +commit(query)
    +rollback()
    -_requestDone(promise)
    -_onSuccess()
    -_onError()
    -_reset()
}

class CypherResult {
    ~constructor(@response)
    +response
    +rows
    +columns
    +isTextOnly
    -_setStats(@stats)
}

CypherService --> CypherTransaction
CypherService --> CypherResult
'CypherTransaction --> CypherResult

@enduml